In [1]:
from data import *
from models import *

In [2]:
net = BasicNet(in_c=1)
loader = get_loader('data/', batch_size=1, mono=True, train=False)

In [3]:
x, y = next(iter(loader))
print(x.shape, y.shape)

torch.Size([1, 1, 9, 9]) torch.Size([1, 9, 9])


In [4]:
y_hat = net(x.float())
print(y_hat.shape)

torch.Size([1, 81, 9])


In [18]:
argmax = torch.stack([torch.argmax(item) for item in y_hat]).unsqueeze(1)
# argmax = torch.argmax(y_hat[0])
argmax

tensor([[583]])

In [19]:
maxes = [torch.max(item) for item in y_hat]
maxes

[tensor(2.1873, grad_fn=<MaxBackward1>)]

In [13]:
dims = (argmax // 9) % 9
dims

tensor([[3],
        [1]]) tensor([[4],
        [3]])


tensor([[3],
        [1]])

In [31]:
y_hat[0, (583%9)]

tensor([ 0.3390, -0.5958, -0.0164, -0.5197,  0.0516,  0.1778, -0.0203, -0.3135,
         0.1799], grad_fn=<SelectBackward>)

In [30]:
y[:, middle_dim, last_dim]

tensor([[5., 8.],
        [4., 2.]], dtype=torch.float64)

In [32]:
objective = nn.CrossEntropyLoss()

In [34]:
loss = objective(y_hat.transpose(1,2), y.reshape((-1, 81)).long())
loss.item()

2.5009632110595703

In [5]:
print_tensor_puzzle(y_hat[0].reshape(9,9,9))

|-------|-------|-------|
| 1 1 0 | 8 2 8 | 2 4 2 | 
| 4 2 2 | 7 6 7 | 5 1 0 | 
| 1 5 4 | 0 6 4 | 2 0 0 | 
|-------|-------|-------|
| 7 2 8 | 3 7 4 | 0 1 5 | 
| 6 3 3 | 5 3 6 | 0 1 5 | 
| 0 1 0 | 4 4 8 | 1 4 7 | 
|-------|-------|-------|
| 5 3 4 | 4 5 4 | 5 6 3 | 
| 5 6 0 | 2 4 0 | 8 1 7 | 
| 1 2 5 | 5 8 0 | 3 4 8 | 
|-------|-------|-------|
