In [1]:
import numpy as np
from env import GridEnv

In [2]:
env = GridEnv('~/school/drl-sudoku/data/sudoku.csv', max_len=500000)
state, goal = env.reset()
# goal = np.asarray([
#     [1,2,3,4,5,6,7,8,9],
#     [2,3,4,5,6,7,8,9,1],
#     [3,4,5,6,7,8,9,1,2],
#     [4,5,6,7,8,9,1,2,3],
#     [5,6,7,8,9,1,2,3,4],
#     [6,7,8,9,1,2,3,4,5],
#     [7,8,9,1,2,3,4,5,6],
#     [8,9,1,2,3,4,5,6,7],
#     [9,1,2,3,4,5,6,7,8]
# ]) - 1
# goal = goal
print(goal.shape)

# state = np.asarray([
#     [0,2,3,4,5,6,7,8,9],
#     [2,3,4,5,6,7,8,9,1],
#     [3,4,5,6,7,8,9,1,2],
#     [4,5,6,7,8,9,1,2,3],
#     [5,6,7,8,9,1,2,3,4],
#     [6,7,8,9,1,2,3,4,5],
#     [7,8,9,1,2,3,4,5,6],
#     [8,9,1,2,3,4,5,6,7],
#     [9,1,2,3,4,5,6,7,8]
# ])
print(state.shape)

(9, 9)
(9, 9, 9)


In [3]:
print(state, '\n\n', goal)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  

In [6]:
import random

for _ in range(5):
    a = random.randrange(0, 9*81)
    _, r, _ = env.act(state, a, goal)
    print(f'Reward:{r}')

1 6 2
Reward:-2
8 2 8
Reward:-1
1 8 8
Reward:-1
3 0 2
Reward:0
7 8 4
Reward:0


In [5]:
state[1, :, :]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])