# Environment Setup

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
!cp /content/gdrive/My\ Drive/data/*.zip .
!unzip /content/sudoku.zip
!unzip /content/sudoku_test.zip

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive
Archive:  /content/sudoku.zip
  inflating: sudoku.csv              
Archive:  /content/sudoku_test.zip
replace sudoku.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [2]:
!git clone https://github.com/cloughurd/drl-sudoku.git
!mv drl-sudoku/data/* .

Cloning into 'drl-sudoku'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 41 (delta 12), reused 22 (delta 5), pack-reused 0
Unpacking objects: 100% (41/41), done.


In [0]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
import matplotlib.pyplot as plt
import librosa
import os
import gc
import wave
import struct
import math
import contextlib
from mido import MidiFile
from mido.messages.messages import Message
import mido
from typing import List
from tqdm import tqdm
import random
from torch.utils.data.sampler import SubsetRandomSampler


from IPython.core.ultratb import AutoFormattedTB
__ITB__ = AutoFormattedTB(mode = 'Verbose',color_scheme='LightBg', tb_offset = 1)

# Create dataloader

In [0]:
def normalize_mono_grid(m):
  return (m / 9.0) - 0.5

In [0]:
from dataloader import *

loader = get_loader(root="/content/", batch_size=1, mono=True, train=True)

In [0]:
x, y = next(iter(loader))

# Define Model

In [0]:
class Reshape(nn.Module):
    def __init__(self, shape):
        super(Reshape, self).__init__()
        self.shape = shape

    def forward(self, x):
        return x.view(self.shape)

In [0]:
class ToSudokuRange(nn.Module):
  def __init__(self):
    super(ToSudokuRange, self).__init__()
    self.sigmoid = nn.Sigmoid()
    self.net = lambda x: (9 * self.sigmoid(x)) + 0.5
  
  def forward(self, x):
    return self.net(x)

In [0]:
class SolverLayer(nn.Module):
  def __init__(self, in_filters:int, hidden_filters:int, out_filters:int):
    super(SolverLayer, self).__init__()

    self.initial_normalization = nn.InstanceNorm2d(in_filters) # Normalize every individual game within its filters. Not positive this is a good idea... maybe use the 3d version?

    self.HorizontalDependencies = nn.Sequential(        
        nn.Conv2d(in_filters, hidden_filters, kernel_size=(9, 1)), # Output is 1, 9.
        nn.LeakyReLU(),
        Reshape((-1, hidden_filters, 9)),
        # Make into a full board shape that can be recombined... Maybe?
        nn.Linear(9, 81), 
        Reshape((-1, hidden_filters, 9, 9)),
        nn.LeakyReLU()
    )

    self.VerticalDependencies = nn.Sequential(
        nn.Conv2d(in_filters, hidden_filters, kernel_size=(1, 9)), # Output is 9, 1.
        nn.LeakyReLU(),
        Reshape((-1, hidden_filters, 9)),
        # Make into a full board shape that can be recombined... Maybe?
        nn.Linear(9, 81), 
        Reshape((-1, hidden_filters, 9, 9)),
        nn.LeakyReLU()
    )

    self.QuadrantDependencies = nn.Sequential(
        nn.Conv2d(in_filters, hidden_filters, kernel_size=(3, 3), stride=3),
        nn.LeakyReLU(),
        Reshape((-1, hidden_filters, 9)),
        # Make into a full board shape that can be recombined... Maybe?
        nn.Linear(9, 81), 
        Reshape((-1, hidden_filters, 9, 9)),
        nn.LeakyReLU()
    )

    self.Reduce = nn.Sequential(
        nn.Conv2d(hidden_filters * 3, out_filters, kernel_size=(1, 1)), # Look at each cell only, without neighbors; neighbors have already been considered.
        nn.LeakyReLU()
    )

  def forward(self, x):
    x = self.initial_normalization(x)
    horizontal_result = self.HorizontalDependencies(x)
    vertical_result = self.VerticalDependencies(x)
    quadrant_result = self.QuadrantDependencies(x)

    combined = torch.cat((horizontal_result, vertical_result, quadrant_result), dim=1)
    reduced = self.Reduce(combined)
    return reduced
    


In [0]:
class MonoModel(nn.Module):
  def __init__(self, solver_depth:int):
    super(MonoModel, self).__init__()
    self.net = nn.Sequential(
        # Give a channel dimension
        Reshape((-1, 1, 9, 9)),
        SolverLayer(1, 9, 9),
        *[ SolverLayer(9, 9, 9) for _ in range(solver_depth - 2)],
        SolverLayer(9, 9, 1),
        Reshape((-1, 9, 9)),
        ToSudokuRange()
    )

  def forward(self, x):
    return self.net(x)

In [0]:
def puzzle_exactifier(p):
  return torch.round(p)

def puzzle_masker(attempts, starting_puzzles):
  assert attempts.size() == starting_puzzles.size()
  num_filled_in_solution = torch.sum(starting_puzzles != 0).item()
  attempts = torch.where(starting_puzzles == 0, attempts, starting_puzzles)
  return (attempts, starting_puzzles, num_filled_in_solution)

def solved_accuracy(attempts, solutions, starting_puzzles):
  assert attempts.size() == solutions.size()
  masked_puzzle, _, _ = puzzle_masker(attempts, starting_puzzles)
  print(masked_puzzle, solutions, starting_puzzles)
  num_puzzles = attempts.size(0)
  num_correct = (masked_puzzle.eq(solutions).sum(1).sum(1) == 9).sum().item()
  return num_correct / num_puzzles

def cell_accuracy(attempts, solutions, starting_puzzles):
  assert attempts.size() == solutions.size()
  masked_puzzle, _, num_filled = puzzle_masker(attempts, starting_puzzles)
  print(masked_puzzle, solutions, starting_puzzles)
  num_cells = attempts.numel()
  num_correct = masked_puzzle.eq(solutions).sum().item()
  num_guessed_correctly = num_correct - num_filled
  return num_guessed_correctly / num_cells


# Training Loop

In [0]:
model = MonoModel(9)

In [44]:
loop = tqdm(range(10))

  0%|          | 0/10 [00:00<?, ?it/s]

In [0]:
def train(model:MonoModel, criterion:torch.nn.modules.loss._Loss, optimizer:torch.optim.Optimizer, train_loader:DataLoader, valid_loader:DataLoader, num_epochs:int, valid_frequency:int=5):
  loop = tqdm(total=num_epochs * len(train_loader) + (num_epochs // valid_frequency) * len(valid_loader), position=0)

  # The loss of the last training and validation iteration, respectively.  
  train_loss = None
  valid_loss = None

  # The puzzle accuracy of the last training and validation itersions. ( # puzzles right / # puzzles total )
  train_accuracy = None
  valid_accuracy = None

  # The cell accuracy of the last training and validation iterations ( # filled cells right / # num fillable cells )
  train_inner_acc = None
  valid_inner_acc = None

  for e in range(num_epochs):

    training_losses = []
    training_accuracies = []
    training_cell_accuracies = []

    loop.set_description(f"[Training] Epoch: {e}. Loss: {valid_loss}/{train_loss}. Total Accuracy: {train_accuracy}/{valid_accuracy}. Inner Accuracy: {train_inner_acc}/{valid_inner_acc}")

    for puzzle, solution in loader:
      puzzle, solution = puzzle.cuda(async=False), solution.cuda(async=False)
      initial_puzzle = puzzle.copy()

      optimizer.zero_grad()
      attempt = model(puzzle)
      loss = criterion(attempt, solution)

      loss.backward()
      optimizer.step()

      train_loss = loss.item()
      training_losses.append(train_loss)

      # Compute accuracies
      exactified = puzzle_exactifier(attempt)

      solved_accuracy = solved_accuracy(exactified, solution, initial_puzzle)
      cell_accuracy = cell_accuracy(exactified, solution, initial_puzzle)

      train_accuracy = solved_accuracy
      training_accuracies.append(train_accuracy)

      train_inner_acc = cell_accuracy
      training_inner_accuracies.append(train_inner_acc)
      



# TEST ACCURACY METRIC METHODS

In [101]:
j = torch.Tensor([[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]]])
k = torch.Tensor([[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]]])
l = torch.Tensor([[[2,2,2],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]]])

z = torch.zeros((3,3,3))
f = z.clone()
f[:,:,0] = k[:,:,0]
g = z.clone()
g[:,:,0] = l[:,:,0]

tensor([[[2., 0., 0.],
         [2., 0., 0.],
         [3., 0., 0.]],

        [[1., 0., 0.],
         [2., 0., 0.],
         [3., 0., 0.]],

        [[1., 0., 0.],
         [2., 0., 0.],
         [3., 0., 0.]]])


In [104]:
print(l)
print(cell_accuracy(j, l, g))

tensor([[[2., 2., 2.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]]])
tensor([[[2., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]]]) tensor([[[2., 2., 2.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]]]) tensor([[[2., 0., 0.],
         [2., 0., 0.],
         [3., 0., 0.]],

        [[1., 0., 0.],
         [2., 0., 0.],
         [3., 0., 0.]],

        [[1., 0., 0.],
         [2., 0., 0.],
         [3., 0., 0.]]])
Correct: <class 'int'>
Num cells: <class 'int'>
0.5925925925925926


In [68]:
f

tensor([[[1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.]],

        [[1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.]],

        [[1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.]]])